# Built with Jekyll 3.2.0

# Setup
title:               'Transcriptions @ W&L'
tagline:             'A Jekyll theme for minimal editions'
description:         'Transcriptions @ W&L provides a clean reading interface for documents in our collections.'
url:                 'http://www.mackenziekbrooks.info'
baseurl:             '/spt'

# About/contact
author:
  name:              Mackenzie Brooks
  url:               http://library.wlu.edu
  email:             brooksm@wlu.edu

# Permalinks

permalink: pretty
permalink: /:title/

# Set encoding to UTF-8
encoding: utf-8


# Collections for texts
collections:
  texts:
    output: true

# Markdown specs
markdown: kramdown

kramdown:
  auto_ids:       true
  footnote_nr:    1
  entity_output:  as_char
  footnote_backlink: "&#x21a9;&#xfe0e;"
  toc_levels:     1..6
  smart_quotes:   lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# Custom vars
version:             0.0.6

# Exclusions from the final site
exclude: [optional, vendor]


